config/routes.rb
Rails.application.routes.draw do


  get 'addpick' => 'picks#new'
  get 'signup' => 'users#new'
  get 'allpicks'    => 'picks#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
 root 'sessions#new'
resources :users
resources :picks

end

app/models/pick.rb
class Pick < ActiveRecord::Base

	def pick_params
  		params.require(:pick).permit(:round, :pick, :user, :team, :player)
  	end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  def forget
    update_attribute(:remember_digest, nil)
  end
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def user_params
      params.require(:user).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  #before_action :logged_in_user, only: [:index]
  @round = 0
  @pickNumber = 0

  def new
  	@pick = Pick.new
  	@user = current_user
  	@round = last_round
    @pickNumber = last_pick
    if(@pickNumber == 5)
        @round +=1
        @pickNumber=1
    elsif @pickNumber !=1
        @pickNumber+=1
    end
    @team = next_team(@pickNumber, @round)
  end

  def create
    @pick = Pick.new(pick_params)
    if @pick.save
      flash[:success] = "Pick Added!"
      redirect_to allpicks_path
    else
      render 'new'
    end
  end

  def index
  	@picks = Pick.all
    @round = last_round
    @pickNumber = last_pick
  end

  private
  	def pick_params
  		params.require(:pick).permit(:round, :pick, :user, :team, :player)
  	end
    def last_round
      last_pick = Pick.order("created_at").last
      
      if(last_pick == nil)
        return 1
      end
      last_round = last_pick.round
    end
    def last_pick
        last_pick = Pick.order("created_at").last
        if (last_pick == nil)
          return 1
        end
        l_pick = last_pick.pick
    end
    def next_team (pickNum,roundNum)
      oddTeam = ["Team 1","Team 2","Team 3","Team 4","Team 5"]
      evenTeam = oddTeam.reverse
      pickNum -=1
      if(roundNum%2 == 0)
        return evenTeam[pickNum]
      else
        return oddTeam[pickNum]
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	  user = User.find_by(name: params[:session][:name])
    if user 
        log_in user
        redirect_back_or allpicks_path

	else
      flash.now[:danger]= 'Invalid name' # Not quite right!
      render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def create
  	 @user = User.new(user_params)  
    if @user.save
      redirect_to root_path
  	else
  		render 'new'
  	end
  end

  
  private 

  	def user_params
  		params.require(:user).permit(:name)
  	end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end
	def current_user
  		if (user_id = session[:user_id])
    		@current_user ||= User.find_by(id: user_id)
		  end
  end
  	def logged_in?
  		!current_user.nil?
  	end# Forgets a persistent session.
  	def forget(user)
    	user.forget
  	end

  	# Logs out the current user.
  	def log_out
    	forget(current_user)
    	session.delete(:user_id)
    	@current_user = nil
  	end
  	def current_user?(user)
   	 user == current_user
  	end
    # Redirects to stored location (or to the default).
  	def redirect_back_or(default)
    	redirect_to(session[:forwarding_url] || default)
    	session.delete(:forwarding_url)
  	end

  	# Stores the URL trying to be accessed.
  	def store_location
    	session[:forwarding_url] = request.url if request.get?
  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DraftProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/picks/_pick.html.erb
<tr>
	<td><%= pick.round %></td> <td><%= pick.pick %></td> <td><%= pick.user %></td>  <td><%= pick.team %></td> <td><%= pick.player %></td>
<tr>

app/views/picks/index.html.erb
<h1>The Draft</h1>
<%= link_to "Add Pick", addpick_path unless @round >=25 and @pickNumber>=5%>
<table class="picks">
	<tr>
		<th>Round</th>
		<th>Pick</th>
		<th>User</th>
		<th>Team</th>
		<th>Player</th>
	<tr>
  <%= render @picks %>
</table>
<%= link_to "Add Pick", addpick_path unless @round >=25 and @pickNumber>=5%>

app/views/picks/new.html.erb
<h1>Add Pick</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@pick) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :round %>
      <%= f.text_field :round, class: 'form-control smallTF', :value => @round.to_s, :readonly => true %>

      <%= f.label :pick %>
      <%= f.text_field :pick, class: 'form-control smallTF', :value => @pickNumber.to_s, :readonly => true%>

      <%= f.label :user %>
      <%= f.text_field :user, class: 'form-control', :value => @user.name_before_type_cast, :readonly => true%>

      <%= f.label :team %>
      <%= f.text_field :team, class: 'form-control medTF', :value => @team, :readonly => true %>

      <%= f.label :player %>
      <%= f.text_field :player, class: 'form-control' %>

      <%= f.submit "Add My Pick", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= user.name %>

app/views/users/new.html.erb
<h1>Please Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>